# Generated by Django 4.2.3 on 2023-07-18 14:52

from django.db import migrations
import task_manager.managers


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                ("objects", task_manager.managers.CustomUserManager()),
            ],
        ),
    ]
