# Generated by Django 4.2.3 on 2023-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_employee_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(choices=[(0, "Low"), (1, "Medium"), (2, "High")]),
        ),
    ]
