# Generated by Django 4.2.3 on 2023-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0004_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
