# Generated by Django 4.2.3 on 2023-07-22 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_employee_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
