# Generated by Django 4.2.3 on 2023-08-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name']},
        ),
    ]
